### ISSUE TITLE
code not working aftere implimentation

### ISSUE THREAD

**Issue by nikhiljahagirdar** [FenrirUnbound/flipit#61]
used you sample code as it is given in the sample and config json file is copied to config folder in sails js application. getting following error. need your help

error: A hook (`controllers`) failed to lo
error: Error: watch testConfigurationFile.
    at exports._errnoException (util.js:87
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at Object.load (C:\ToggleFeatureSample
it\lib\feature-loader.js:12:15)
    at Object.load (C:\ToggleFeatureSample
it\index.js:41:26)
    at Object.<anonymous> (C:\ToggleFeatur
llers\TestfeatureController.js:14:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (modu
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:30
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\nodejs\node_modules\sails\node_m
    at Array.forEach (native)
    at requireAll (C:\nodejs\node_modules\
s:44:9)
    at buildDictionary (C:\nodejs\node_mod
ctionary\index.js:68:14)

**Comment by FenrirUnbound** [comment]
Hi @nikhiljahagirdar 

Sorry to hear that you're experiencing issues with the module. Let's see if I can help.

Based on the error message, it seems like it cannot find the `testConfigurationFile.json` file. You also mentioned:

>  "...config json file is copied to config folder..."

The example posted in the README assumes that the sample script and the `testConfigurationFile.json` file are in the same folder. Have you tried updating the `flipit.load` filepath so that it's pointing to the correct json file?

**Comment by FenrirUnbound** [comment]
Hi @nikhiljahagirdar ,

It has been some time since you opened this issue and have been given a response. I'll close this issue, since it does not seem like it's an issue that's blocking you.
